name: juejin
description: Xitu Juejin APP on Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  device_info_plus: ^4.0.0
  dio: ^4.0.6
  equatable: ^2.0.3
  ff_annotation_route_library: ^3.0.0
  flutter_displaymode: ^0.4.0
  flutter_markdown: ^0.6.10+3
  flutter_svg: ^1.1.1+1
  intl: any
  json_annotation: ^4.6.0
  logging: ^1.0.2
  oktoast: ^3.2.0
  open_file: ^3.2.1
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  url_launcher: ^6.1.5

dev_dependencies:
  archive: ^3.3.0
  args: ^2.3.1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  path: ^1.8.2
  process_run: ^0.12.3+2
  yaml: ^3.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
